### ISSUE TITLE
Crossed double bond in MOL turned into defined stereo in CDXML

### ISSUE THREAD

**Issue by baoilleach** [kienerj/pycdxml#25]
[CHEMBL4207369.mol.txt](https://github.com/kienerj/pycdxml/files/10042408/CHEMBL4207369.mol.txt) has a crossed double bond visible in ChemDraw when opened.
![image](https://user-images.githubusercontent.com/45337/202736542-c5c782fc-5940-49e6-9c4b-477a70c89950.png)
However, this is converted to a regular double bond by PyCDXML:
![image](https://user-images.githubusercontent.com/45337/202736660-e85d8c86-f6be-457b-a9b0-9c4f93700542.png)

**Comment by kienerj** [comment]
That is likley due that I recently added the `crossed_bonds=False` argument. Setting it to True fixes the issue. 

Depending on usage of the output often being used for visualization and at least some users don't like seeing crossed bonds, I defaulted to displaying as normal bond. But I'm open to reversing the default. 

(Due to different regulations for different industries "stereochemical exactness"  might be less important especially if you can sell the molecule as "mixture of isomers")

Leaving it open to discuss about the default value.

**Comment by baoilleach** [comment]
Ok - I must doublecheck, because I thought I was setting it to True.

Regarding the default, I would recommend that the defaults preserve information as much as possible - otherwise it's a bit of a surprise when it happens. If people don't want to see the crossed double bond, and wish to discard that information, then they should need to actively choose that option.

**Comment by kienerj** [comment]
Changed default to `crossed_bonds=True` in 16b8f2828daef24dac9b8658d6b3bd12b92375da

**Comment by baoilleach** [comment]
Double-checked, and indeed it was working.
